# Export multi-objective result data

### Read results

In [1]:
import os
import pickle
os.chdir('..')
file = open("HallOfFame.pkl", "rb") 
hall_of_fame = pickle.load(file)
file.close()
os.chdir('src')

### Export results

In [2]:
tac = list()
ghg = list()
cap = list()
cop = list()

for k in range(len(hall_of_fame)):
    for i in range(len(hall_of_fame[k])):
        tac.append(hall_of_fame[k][i][1].total_annual_cost)
        ghg.append(hall_of_fame[k][i][1].operating_emissions)
        cap.append(hall_of_fame[k][i][1].capital_costs * hall_of_fame[k][i][1].economics.annuity_factor)
        cop.append(hall_of_fame[k][i][1].operating_costs)


### Find best solution based on objective

In [3]:
import numpy as np
tac_min = np.min(tac)
ghg_min = np.min(ghg)
cap_min = np.min(cap)
cop_min = np.min(cop)

for k in range(len(hall_of_fame)):
    for i in range(len(hall_of_fame[k])):
        if abs(hall_of_fame[k][i][1].total_annual_cost - tac_min < 0.1):
            print('TAC_min:',round(tac_min,2),'CHF/y HoF:',k,'Front:',i)
            tac_min_index = [k,i]
        if abs(hall_of_fame[k][i][1].operating_emissions - ghg_min < 0.1):
            print('GHG_min:',round(ghg_min,2),'t_CO2e/y HoF:',k,'Front:',i)
            ghg_min_index = [k,i]
        if abs(hall_of_fame[k][i][1].capital_costs * hall_of_fame[k][i][1].economics.annuity_factor - cap_min < 0.1):
            print('CAP_min:',round(cap_min,2),'CHF/y HoF:',k,'Front:',i)
            cap_min_index = [k,i]
        if abs(hall_of_fame[k][i][1].operating_costs - cop_min < 0.1):
            print('COP_min:',round(cop_min,2),' CHF/y HoF:',k,'Front:',i)
            cop_min_index = [k,i]

CAP_min: 11177.56 CHF/y HoF: 13 Front: 0
TAC_min: 61779.47 CHF/y HoF: 99 Front: 1
GHG_min: 48.43 t_CO2e/y HoF: 99 Front: 1
COP_min: 21947.62  CHF/y HoF: 99 Front: 1


### Extract results

#### Print results based on selected objective

In [6]:
hof = tac_min_index[0]
front = tac_min_index[1]
# hof = ghg_min_index[0]
# front = ghg_min_index[1]
# hof = cap_min_index[0]
# front = cap_min_index[1]
# hof = cop_min_index[0]
# front = cop_min_index[1]
print('TAC:',hall_of_fame[hof][front][1].total_annual_cost,'CHF/y')
print('GHG:',hall_of_fame[hof][front][1].operating_emissions,'t_CO2e/y')
print('CAP:',hall_of_fame[hof][front][1].capital_costs * hall_of_fame[k][i][1].economics.annuity_factor,'CHF/y')
print('COP:',hall_of_fame[hof][front][1].operating_costs,'CHF/y')
print('EAM:')
print(hall_of_fame[hof][front][2])
print('Heat load distributions [kW]:')
print(np.array(hall_of_fame[hof][front][0]))
print('Hot utility:',sum(hall_of_fame[hof][front][1].hot_utility_demand),'kWh')
print('Cold utility:',sum(hall_of_fame[hof][front][1].cold_utility_demand),'kWh')

TAC: 61779.4702907553 CHF/y
GHG: 48.43231773743359 t_CO2e/y
CAP: 39831.85177871187 CHF/y
COP: 21947.618512043427 CHF/y
EAM:
[[0 0 2 0 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 4 1 1 0 0 0 1]
 [1 1 1 1 0 0 0 1]
 [2 4 0 0 0 0 0 1]
 [0 3 0 1 0 0 0 1]
 [1 2 2 0 0 1 1 1]]
Heat load distributions [kW]:
[[233.4175394  242.6515871 ]
 [  0.           0.        ]
 [  0.         174.03876225]
 [ 42.74208622  43.01043958]
 [  0.          10.86391828]
 [  0.         246.38024517]
 [ 28.9574229   18.81166445]]
Hot utility: 201356.6787625446 kWh
Cold utility: 145977.1052759965 kWh


#### Print relating heat exchanger areas

In [5]:
print('needed heat exchanger areas [m^2]:')
for k in range(len(hall_of_fame[hof][front][1].heat_exchangers)):
    print(hall_of_fame[71][0][1].heat_exchangers[k].operation_parameter.needed_areas)

needed heat exchanger areas [m^2]:
[0. 0.]
[0. 0.]
[0. 0.]
[0.         2.84798357]
[0. 0.]
[0.40524295 0.41764692]
[0.         0.65633671]
